# Generated by Django 5.2.6 on 2026-03-07 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0042_alter_donationtransactions_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Amount', models.SmallIntegerField(default=1)),
                ('PaidAmount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('RemainingAmount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('UpdateTime', models.DateTimeField(auto_now=True)),
                ('Status', models.IntegerField(choices=[(0, 'ORDER_PLACED'), (1, 'PROCESSING'), (2, 'SHIPPED'), (3, 'DELIVERED')])),
                ('Installment', models.BooleanField(default=False)),
                ('Last_Transcation', models.BooleanField(default=False)),
                ('RequestOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OwnedRequest', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Text', models.TextField(null=True)),
                ('Stars', models.FloatField(default=0)),
                ('Reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Reviewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Tag', models.CharField(max_length=50, unique=True)),
                ('StoreOwner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreOwner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreAttachments',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='NO_NAME')),
                ('Attachments', models.FileField(default=None, null=True, upload_to='uploads/store/')),
                ('attachmentLicence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='StoreAttachments', to='core.attachmentlicence')),
            ],
        ),
        migrations.CreateModel(
            name='StoreItems',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Serial', models.CharField(unique=True)),
                ('Stars', models.FloatField(default=0)),
                ('Price', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Amount', models.IntegerField(default=0)),
                ('ReviewsCount', models.IntegerField(default=0)),
                ('attachments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='StoreItems', to='store.storeattachments')),
            ],
        ),
        migrations.CreateModel(
            name='Catigories',
            fields=[
                ('Name', models.CharField(max_length=50)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('StoreItems', models.ManyToManyField(related_name='Catigories', to='store.storeitems')),
            ],
        ),
        migrations.CreateModel(
            name='storePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('TransactionType', models.IntegerField(choices=[(0, 'ORDER_PLACED'), (1, 'PROCESSING'), (2, 'SHIPPED'), (3, 'DELIVERED')])),
                ('PaidRequest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payments', to='store.requests')),
                ('PaidUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paidUser', to=settings.AUTH_USER_MODEL)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storePayment', to='core.paymentlocker')),
            ],
        ),
    ]
