# Generated by Django 5.2.6 on 2026-04-12 18:56

import core.services.types.questionType
import core.services.utils.notification
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dependenciesRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependentTable', models.TextField()),
                ('dependOnTable', models.TextField()),
                ('allowedFields', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Messages_Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='uploads/chats/')),
            ],
        ),
        migrations.CreateModel(
            name='paymentLocker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalAmount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('lastUpdate', models.DateTimeField()),
                ('count', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='shareWithLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableName', models.TextField()),
                ('address', models.TextField()),
                ('itemID', models.IntegerField()),
                ('command', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='supportedLanguages',
            fields=[
                ('Name', models.CharField(max_length=2)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttachmentLicence',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('uploadTime', models.DateTimeField(auto_now=True)),
                ('FileFingerPrint', models.TextField()),
                ('RequireSecurity', models.BooleanField(default=False)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachmentLicence', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='classRoom',
            fields=[
                ('paymentAmount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('PaymentExpireInterval_MIN', models.IntegerField(default=0)),
                ('PaymentAccessMaxCount', models.IntegerField(default=0)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(default='', max_length=50, null=True)),
                ('HideFromSearch', models.BooleanField(default=False)),
                ('attachmentsCounter', models.IntegerField(default=0)),
                ('createAt', models.DateField(auto_now=True)),
                ('OwnedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OwnedClasses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='chatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymentAmount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('PaymentExpireInterval_MIN', models.IntegerField(default=0)),
                ('PaymentAccessMaxCount', models.IntegerField(default=0)),
                ('Name', models.CharField(max_length=50)),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatRooms', to='core.classroom')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='classRoom_ClassRoomAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('isOrderDepenent', models.BooleanField(default=False)),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_clAttach', to='core.classroom')),
            ],
        ),
        migrations.CreateModel(
            name='ClassRoomAttachment',
            fields=[
                ('paymentAmount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('PaymentExpireInterval_MIN', models.IntegerField(default=0)),
                ('PaymentAccessMaxCount', models.IntegerField(default=0)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField(default='NO_NAME')),
                ('order', models.IntegerField(default=0)),
                ('isOrdered', models.BooleanField(default=False)),
                ('Attachments', models.FileField(default=None, null=True, upload_to='uploads/data/classRoom/')),
                ('thumbnail', models.FileField(default=None, null=True, upload_to='uploads/thumbnails/classRoom')),
                ('attachmentLicence', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classRoomAttachment', to='core.attachmentlicence')),
                ('classRoom', models.ManyToManyField(related_name='Attachments', through='core.classRoom_ClassRoomAttachment', to='core.classroom')),
                ('otherAttachmets', models.ManyToManyField(related_name='relatedAttachment', to='core.classroomattachment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='classroom_classroomattachment',
            name='ClassRoomAttachment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_clAttach', to='core.classroomattachment'),
        ),
        migrations.CreateModel(
            name='AttachmentDependencies',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('jsonDep', models.JSONField()),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core.classroomattachment')),
            ],
        ),
        migrations.CreateModel(
            name='Committe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOpened', models.BooleanField(default=False)),
                ('isInspectorIn', models.BooleanField(default=False)),
                ('isExamStarted', models.BooleanField(default=False)),
                ('clRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteAllowedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('committe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.committe')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowedIn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventStr', models.TextField()),
                ('committe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='core.committe')),
            ],
        ),
        migrations.CreateModel(
            name='donationTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerName', models.CharField(blank=True, max_length=150)),
                ('Datetime', models.DateTimeField(default=datetime.datetime(2026, 4, 12, 20, 56, 35, 409866))),
                ('Method', models.CharField(blank=True, max_length=50)),
                ('Amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Type', models.IntegerField(choices=[(0, 'PAYMENT'), (1, 'REFUND')])),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='donationBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('lastTransaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.donationtransactions')),
            ],
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalMark', models.FloatField(default=0)),
                ('PassKey', models.TextField(blank=True, null=True)),
                ('Title', models.TextField(blank=True, null=True)),
                ('CreatedAt', models.DateTimeField(default=datetime.datetime(2026, 4, 12, 20, 56, 35, 400781))),
                ('PreventOtherTabs', models.BooleanField(default=True)),
                ('Duration_min', models.IntegerField(default=0)),
                ('AutoCorrect', models.BooleanField(default=True)),
                ('QuestionByQuestion', models.BooleanField(default=True)),
                ('ShareWith', models.IntegerField(choices=[(0, 'CLASSROOM_DEFAULT'), (1, 'ANY_ONE_WITH_LINK'), (2, 'PRIVATE'), (3, 'CLASSROOM_PUBLIC')], default=False)),
                ('AllowDownLoad', models.BooleanField(default=False)),
                ('StartAt', models.DateTimeField(blank=True, null=True)),
                ('EndAt', models.DateTimeField(blank=True, null=True)),
                ('Owner', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Exams', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='committe',
            name='Exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam'),
        ),
        migrations.CreateModel(
            name='classRoom_Exam',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('Exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='Exams',
            field=models.ManyToManyField(related_name='ClassRooms', through='core.classRoom_Exam', to='core.exam'),
        ),
        migrations.CreateModel(
            name='Exam_BlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.TextField(blank=True, null=True)),
                ('exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExamBlackListTable', to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExamBlackListTable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='blackListedStudents',
            field=models.ManyToManyField(related_name='blackListed', through='core.Exam_BlackList', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('User', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Lectures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Xaxis', models.FloatField()),
                ('Yaxis', models.FloatField()),
                ('buildingArea', models.FloatField()),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Locations', to='core.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('destination_Code', models.TextField()),
                ('reading_status', models.IntegerField(choices=[(0, 'PENDING'), (1, 'ARRIVED'), (2, 'READED'), (3, 'DELETED')], default=core.services.utils.notification.NotificationStatus['PENDING'])),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='core.chatroom')),
                ('chatRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.messages')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.notification')),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='Notifications',
            field=models.ManyToManyField(related_name='chatRoom', through='core.Messages', to='core.notification'),
        ),
        migrations.CreateModel(
            name='Payment_ChatRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionTime', models.DateTimeField(auto_now=True)),
                ('ExpireDateTime', models.DateTimeField(blank=True, null=True)),
                ('AccessCounter', models.BigIntegerField(blank=True, null=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_ChatRoom', to=settings.AUTH_USER_MODEL)),
                ('chatRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_ChatRoom', to='core.chatroom')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_ChatRoom', to='core.paymentlocker')),
            ],
        ),
        migrations.CreateModel(
            name='Payment_Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExpireDateTime', models.DateTimeField(blank=True, null=True)),
                ('AccessCounter', models.BigIntegerField(blank=True, null=True)),
                ('TransactionTime', models.DateTimeField(auto_now=True)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('classRoomAttachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_Attachment', to='core.classroomattachment')),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_Attachment', to='core.paymentlocker')),
            ],
        ),
        migrations.CreateModel(
            name='PrivilegeMapper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrivilegeMapper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Privileges',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Privilege', models.IntegerField(default=0)),
                ('ClassRooms', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Privileges', to='core.classroom')),
                ('Users', models.ManyToManyField(default=1, related_name='Privileges', through='core.PrivilegeMapper', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='privilegemapper',
            name='Privilege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='PrivilegeMapper', to='core.privileges'),
        ),
        migrations.CreateModel(
            name='Payment_classRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionTime', models.DateTimeField(auto_now=True)),
                ('ExpireDateTime', models.DateTimeField(blank=True, null=True)),
                ('AccessCounter', models.BigIntegerField(blank=True, null=True)),
                ('Amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('locker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_classRoom', to='core.paymentlocker')),
                ('privilegesMapper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payments', to='core.privilegemapper')),
                ('Privilege', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Payment_classRoom', to='core.privileges')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('createdAt', models.DateField(auto_now=True)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Text_Url', models.CharField(max_length=400)),
                ('Type', models.IntegerField(choices=[(0, 'MCQ_ONE_ANS'), (1, 'MCQ_MORE_ANS'), (2, 'WRITTEN_QUETION'), (3, 'COMPLETE')], default=core.services.types.questionType.QuestionType['MCQ_ONE_ANS'])),
                ('Ans', models.CharField(max_length=400)),
                ('InExamCounter', models.IntegerField(default=0)),
                ('Ease', models.IntegerField(choices=[(0, 'EASY'), (1, 'MEDIUM'), (2, 'HARD')], default=core.services.types.questionType.QuestionEase['EASY'])),
                ('scoringMode', models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'MULTI_ANS_ONE_ENOUGH'), (2, 'MULTI_ANS_PARTITION')], default=0)),
                ('Lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to='core.lecture')),
                ('OwnedBy', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField(default=0)),
                ('degree', models.FloatField(default=0)),
                ('sectionName', models.CharField(blank=True, max_length=150, null=True)),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='Questions',
            field=models.ManyToManyField(through='core.Exam_Questions', to='core.question'),
        ),
        migrations.CreateModel(
            name='solutionsSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LastUpdate', models.DateTimeField(default=datetime.datetime(2026, 4, 12, 20, 56, 35, 405571))),
                ('SubmitReason', models.IntegerField(choices=[(0, 'TIME_ENDED'), (1, 'SUBMITTED'), (2, 'KICKED'), (3, 'CONNECTION_LOST'), (4, 'CONNECTION_LOST_TIME_ENDED'), (5, 'BLACKLISTED'), (6, 'CURRENTLY_ACTIVE')])),
                ('SpecifiedTextReason', models.TextField(blank=True)),
                ('IsSubmitted', models.BooleanField(default=False)),
                ('TotalMark', models.FloatField(default=0)),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SolutionSheets', to='core.exam')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solnSheet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Soln',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Content', models.TextField(blank=True)),
                ('Note', models.TextField(blank=True)),
                ('Degree', models.FloatField(default=0.0)),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solns', to='core.question')),
                ('SolvedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solns', to=settings.AUTH_USER_MODEL)),
                ('correctedBy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='youCorrected', to=settings.AUTH_USER_MODEL)),
                ('SolutionSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='core.solutionssheet')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('User', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subjects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectures', to='core.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exams', to='core.subject'),
        ),
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('socketID', models.TextField(default=None, null=True)),
                ('Warnings', models.SmallIntegerField(default=3)),
                ('User', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Settings', to=settings.AUTH_USER_MODEL)),
                ('PreferedLang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profiles', to='core.supportedlanguages')),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('User', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Terms', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='Term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subjects', to='core.term'),
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroomattachment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachmentHistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Years', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='Year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Terms', to='core.year'),
        ),
        migrations.AddField(
            model_name='subject',
            name='Year',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subjects', to='core.year'),
        ),
    ]
