# Generated by Django 5.2.6 on 2025-09-07 20:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IsScheduled', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ExamInterval', models.TimeField()),
                ('AutoCorrect', models.BooleanField(default=True)),
                ('QuestionByQuestion', models.BooleanField(default=True)),
                ('TrackSolutions', models.BooleanField(default=True)),
                ('Public', models.BooleanField(default=False)),
                ('AllowDownLoad', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text_Url', models.CharField(max_length=400)),
                ('Type', models.IntegerField(choices=[(0, 'Choose'), (1, 'Written'), (2, 'Complex')], default=0)),
                ('Ans', models.CharField(max_length=400)),
                ('IsInAnExam', models.BooleanField()),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to='core.lecture')),
            ],
        ),
        migrations.CreateModel(
            name='ExamSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('Setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.setting')),
            ],
            options={
                'unique_together': {('Setting',)},
            },
        ),
        migrations.AddField(
            model_name='exam',
            name='Settings',
            field=models.ManyToManyField(through='core.ExamSetting', to='core.setting'),
        ),
        migrations.CreateModel(
            name='soln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solns', to='core.exam')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solns', to='core.question')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Solns', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='lecture',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lectures', to='core.subject'),
        ),
        migrations.AddField(
            model_name='exam',
            name='Subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exams', to='core.subject'),
        ),
        migrations.AddField(
            model_name='subject',
            name='Term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subjects', to='core.term'),
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Years', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='term',
            name='Year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Terms', to='core.year'),
        ),
    ]
