# Generated by Django 5.2.6 on 2026-01-02 18:28

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 2, 20, 28, 54, 261331)),
        ),
        migrations.CreateModel(
            name='ExamBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Reason', models.TextField(blank=True, null=True)),
                ('exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExamBlackListTable', to='core.exam')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ExamBlackListTable', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='blackListedStudents',
            field=models.ManyToManyField(related_name='blackListed', through='core.ExamBlackList', to=settings.AUTH_USER_MODEL),
        ),
    ]
