# Generated by Django 5.2.6 on 2026-04-13 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 13, 19, 12, 52, 9643)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 13, 19, 12, 52, 1231)),
        ),
        migrations.AlterField(
            model_name='paymentlocker',
            name='lastUpdate',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 4, 13, 19, 12, 52, 5638)),
        ),
    ]
