# Generated by Django 5.2.6 on 2026-01-02 19:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_exam_createdat_examblacklist_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soln',
            name='Content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 2, 21, 31, 16, 487481)),
        ),
    ]
