# Generated by Django 5.2.6 on 2025-12-06 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_subject_year_alter_exam_user_alter_lecture_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='classRoom',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('attachments', models.FileField(upload_to='uploads/')),
                ('allowThirdPartySeen', models.BooleanField(default=False)),
                ('Admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Admin', to=settings.AUTH_USER_MODEL)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classRoomsOwner', to=settings.AUTH_USER_MODEL)),
                ('Students', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='classRoomsMember', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
