# Generated by Django 5.2.6 on 2026-01-12 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_soln_correctedby_alter_donationtransactions_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privileges',
            name='allowAcceessAttachemtsWithoutPayment',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowAccessChatRoomWithoutPayment',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowAccessExam',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowAccessSolnSheet',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowAccessWithoutPayment',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowAddStudentsAccount',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowBanningSolnSheet',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowCorrectingSolnSheet',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowCreateExam',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowCreateStudentAccount',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowCreatingSolnSheet',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowDeleteExam',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowListStudentsAccounts',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowRemoveStudentAccount',
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='allowUpdateExam',
        ),
        migrations.AddField(
            model_name='privileges',
            name='Privilege',
            field=models.IntegerField(default=0, unique=True),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 19, 30, 14, 447823)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 19, 30, 14, 441843)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 19, 30, 14, 445227)),
        ),
    ]
