# Generated by Django 5.2.6 on 2026-01-02 20:11

import django
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_soln_content_alter_exam_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='solutionsSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isSubmitted', models.BooleanField(default=False)),
                ('totalMark', models.FloatField(default=0)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soln')),
                ('soln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
            ],
        ),
        migrations.AddField(
            model_name='solutionssheet',
            name='submitReason',
            field=models.IntegerField(choices=[(0, 'TIME_ENDED'), (1, 'SUBMITTED'), (2, 'KICKED'), (3, 'CONNECTION_LOST'), (4, 'CONNECTION_LOST_TIME_ENDED'), (5, 'BLACKLISTED')], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 2, 22, 11, 20, 283091)),
        ),
    ]
