# Generated by Django 5.2.6 on 2025-12-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Ease',
            field=models.IntegerField(choices=[(0, 'Easy'), (1, 'Medium'), (2, 'Hard')], default=0),
        ),
    ]
