# Generated by Django 5.2.6 on 2026-05-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_chatroom_users_alter_chatroom_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='messages',
            name='event',
            field=models.CharField(choices=[('Typing', 'UserTyping'), ('Sending', 'UserSending'), ('Recording', 'UserRecording'), ('Downloading', 'UserDownloading'), ('Seen', 'UserSeen'), ('Deleted', 'UserDeleted'), ('Edited', 'UserEdited'), ('Reacted', 'UserReacted'), ('Pinned', 'UserPinned'), ('Unpinned', 'UserUnpinned'), ('Left', 'UserLeft'), ('Message', 'UserMessage'), ('Joined', 'UserJoined'), ('Warning', 'SystemWarning'), ('Error', 'SystemError'), ('Info', 'SystemInfo')], default='Message'),
        ),
    ]
