# Generated by Django 5.2.6 on 2026-05-16 17:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_messages_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='ChatRoomID',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='profileID',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
        ),
    ]
