# Generated by Django 5.2.6 on 2026-01-02 22:53

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_solutionssheet_submitreason_alter_exam_createdat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(upload_to='uploads/')),
                ('title', models.TextField(blank=True)),
            ],
        ),
        migrations.RenameField(
            model_name='soln',
            old_name='solutionsSheet',
            new_name='Exam',
        ),
        migrations.AddField(
            model_name='solutionssheet',
            name='student',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='solnSheet', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 0, 53, 41, 695886)),
        ),
    ]
