# Generated by Django 5.2.6 on 2025-12-08 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_question_ease'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='Qindex',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='exam',
            name='Question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Exams', to='core.question'),
            preserve_default=False,
        ),
    ]
