# Generated by Django 5.2.6 on 2026-01-12 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_privileges_allowacceessattachemtswithoutpayment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='soln',
            name='IsCorrect',
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 19, 38, 12, 643448)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 19, 38, 12, 637519)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 19, 38, 12, 640836)),
        ),
    ]
