# Generated by Django 5.2.6 on 2026-01-12 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_soln_iscorrect_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='TotalMark',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 22, 5, 30, 344210)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 22, 5, 30, 336604)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 12, 22, 5, 30, 340924)),
        ),
    ]
