# Generated by Django 5.2.6 on 2026-01-02 23:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_attachments_rename_solutionssheet_soln_exam_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionssheet',
            name='specifiedTextReason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 1, 5, 33, 803720)),
        ),
    ]
