# Generated by Django 5.2.6 on 2025-12-08 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_exam_qindex_exam_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='Qindex',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='Question',
        ),
        migrations.CreateModel(
            name='ExamQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order', models.IntegerField(default=0)),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('Question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
            ],
        ),
        migrations.AddField(
            model_name='exam',
            name='Questions',
            field=models.ManyToManyField(related_name='Exams', through='core.ExamQuestion', to='core.question'),
        ),
    ]
