# Generated by Django 5.2.6 on 2025-12-09 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_exam_qindex_remove_exam_question_examquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='Settings',
        ),
        migrations.DeleteModel(
            name='ExamSetting',
        ),
        migrations.AddField(
            model_name='exam',
            name='Settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.setting'),
            preserve_default=False,
        ),
    ]
