# Generated by Django 5.2.6 on 2026-01-03 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_solutionssheet_specifiedtextreason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solutionssheet',
            name='lastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 11, 58, 56, 935104)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 11, 58, 56, 932142)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='submitReason',
            field=models.IntegerField(choices=[(0, 'TIME_ENDED'), (1, 'SUBMITTED'), (2, 'KICKED'), (3, 'CONNECTION_LOST'), (4, 'CONNECTION_LOST_TIME_ENDED'), (5, 'BLACKLISTED'), (6, 'CURRENTLY_ACTIVE')]),
        ),
    ]
