# Generated by Django 5.2.6 on 2026-01-16 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_exam_totalmark_alter_donationtransactions_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 15, 51, 5, 500174)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 15, 51, 5, 493047)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='ShareWith',
            field=models.IntegerField(choices=[(0, 'CLASSROOM_DEFAULT'), (1, 'ANY_ONE_WITH_LINK'), (2, 'PRIVATE'), (3, 'CLASSROOM_PUBLIC')], default=False),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 16, 15, 51, 5, 496631)),
        ),
    ]
