# Generated by Django 5.2.6 on 2026-01-19 19:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_donationtransactions_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='buildingArea',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 19, 21, 15, 45, 714275)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 19, 21, 15, 45, 708327)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 19, 21, 15, 45, 711679)),
        ),
    ]
