# Generated by Django 5.2.6 on 2025-12-13 13:27

import core.services.types.questionType
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_exam_settings_delete_examsetting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='IsInAnExam',
        ),
        migrations.AddField(
            model_name='question',
            name='InExamCounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='Ease',
            field=models.IntegerField(choices=[(0, 'EASY'), (1, 'MEDIUM'), (2, 'HARD')], default=core.services.types.questionType.QuestionEase['EASY']),
        ),
        migrations.AlterField(
            model_name='question',
            name='Type',
            field=models.IntegerField(choices=[(0, 'MCQ_ONE_ANS'), (1, 'MCQ_MORE_ANS'), (2, 'WRITTEN_QUETION'), (3, 'COMPLEX')], default=core.services.types.questionType.QuestionType['MCQ_ONE_ANS']),
        ),
    ]
