# Generated by Django 5.2.6 on 2026-01-03 15:50

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_solutionssheet_lastupdate_alter_exam_createdat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='solutionssheet',
            old_name='soln',
            new_name='Ans',
        ),
        migrations.RenameField(
            model_name='solutionssheet',
            old_name='exam',
            new_name='Exam',
        ),
        migrations.RenameField(
            model_name='solutionssheet',
            old_name='isSubmitted',
            new_name='IsSubmitted',
        ),
        migrations.RenameField(
            model_name='solutionssheet',
            old_name='specifiedTextReason',
            new_name='SpecifiedTextReason',
        ),
        migrations.RenameField(
            model_name='solutionssheet',
            old_name='student',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='solutionssheet',
            old_name='submitReason',
            new_name='SubmitReason',
        ),
        migrations.RenameField(
            model_name='solutionssheet',
            old_name='totalMark',
            new_name='TotalMark',
        ),
        migrations.RemoveField(
            model_name='solutionssheet',
            name='lastUpdate',
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 17, 50, 34, 698267)),
        ),
        migrations.CreateModel(
            name='balance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='Balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='donationTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OwnerName', models.CharField(blank=True, max_length=150)),
                ('Datetime', models.DateTimeField(default=datetime.datetime(2026, 1, 3, 17, 50, 34, 701295))),
                ('Method', models.CharField(blank=True, max_length=50)),
                ('Amount', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('Type', models.IntegerField(choices=[(0, 'PAYMENT'), (1, 'REFUND')])),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='donationBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('lastTransaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.donationtransactions')),
            ],
        ),
        migrations.AddField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 17, 50, 34, 700893)),
        ),
    ]
