# Generated by Django 5.2.6 on 2026-01-03 21:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_rename_soln_solutionssheet_ans_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='createdAt',
            field=models.DateField(default=datetime.datetime(2026, 1, 3, 23, 1, 54, 458959)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 23, 0, 42, 487345)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 23, 0, 42, 484200)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 23, 0, 42, 486942)),
        ),
    ]
