# Generated by Django 5.2.6 on 2025-12-13 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_question_isinanexam_question_inexamcounter_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam',
            name='Settings',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='attachments',
            new_name='Attachments',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='allowThirdPartySeen',
            new_name='HideFromSearch',
        ),
        migrations.RenameField(
            model_name='exam',
            old_name='User',
            new_name='Owner',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='lecture',
            new_name='Lecture',
        ),
        migrations.RenameField(
            model_name='soln',
            old_name='User',
            new_name='SolvedBy',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='Creator',
        ),
        migrations.RemoveField(
            model_name='exam',
            name='IsScheduled',
        ),
        migrations.AddField(
            model_name='classroom',
            name='OwnedBy',
            field=models.OneToOneField(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='OwnedClasses', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroom',
            name='Teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Teaches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='Admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Adminstrate', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classroom',
            name='Students',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='StudyAt', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Duration', models.TimeField()),
                ('AutoCorrect', models.BooleanField(default=True)),
                ('QuestionByQuestion', models.BooleanField(default=True)),
                ('ShareWith', models.IntegerField(choices=[(0, 'CLASSROOM'), (1, 'ANY_ONE_WITH_LINK'), (2, 'PRIVATE')], default=False)),
                ('AllowDownLoad', models.BooleanField(default=False)),
                ('StartAt', models.DateTimeField(blank=True, null=True)),
                ('EndAt', models.DateTimeField(blank=True, null=True)),
                ('Exam', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Settings', to='core.exam')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Xaxis', models.FloatField()),
                ('Yaxis', models.FloatField()),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Locations', to='core.settings')),
            ],
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
