# Generated by Django 5.2.6 on 2026-01-19 22:03

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_donationtransactions_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privileges',
            name='ChatRoom',
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 0, 3, 54, 397858)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 0, 3, 54, 392972)),
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='ClassRooms',
        ),
        migrations.AlterField(
            model_name='privileges',
            name='Privilege',
            field=models.IntegerField(default=0),
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='User',
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 0, 3, 54, 396287)),
        ),
        migrations.AddField(
            model_name='privileges',
            name='ClassRooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Privileges', to='core.classroom'),
        ),
        migrations.AddField(
            model_name='privileges',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Privileges', to=settings.AUTH_USER_MODEL),
        ),
    ]
