# Generated by Django 5.2.6 on 2025-12-13 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_exam_settings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='Duration',
            new_name='Duration_min',
        ),
    ]
