# Generated by Django 5.2.6 on 2026-01-03 21:04

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_question_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 23, 4, 8, 213448)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 23, 4, 8, 209031)),
        ),
        migrations.AlterField(
            model_name='question',
            name='Lecture',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Questions', to='core.lecture'),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 3, 23, 4, 8, 212831)),
        ),
    ]
