# Generated by Django 5.2.6 on 2026-01-19 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_privileges_chatroom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='Admin',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='Students',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='Teacher',
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 0, 17, 8, 124391)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 0, 17, 8, 119491)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 20, 0, 17, 8, 122790)),
        ),
    ]
