# Generated by Django 5.2.6 on 2026-01-03 22:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_donationtransactions_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='examquestion',
            name='sectionName',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 4, 0, 29, 59, 286775)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 4, 0, 29, 59, 283267)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 4, 0, 29, 59, 286360)),
        ),
    ]
