# Generated by Django 5.2.6 on 2025-12-13 20:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_duration_settings_duration_min'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 13, 22, 31, 2, 348229)),
        ),
        migrations.AddField(
            model_name='exam',
            name='Title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
