# Generated by Django 5.2.6 on 2026-01-03 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_examquestion_sectionname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 4, 0, 30, 9, 668450)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 4, 0, 30, 9, 665368)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 4, 0, 30, 9, 668049)),
        ),
    ]
