# Generated by Django 5.2.6 on 2026-01-05 18:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_donationtransactions_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionssheet',
            name='Ans',
        ),
        migrations.AddField(
            model_name='examquestion',
            name='degree',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='soln',
            name='degree',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='soln',
            name='isCorrect',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='soln',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 5, 20, 59, 27, 561837)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 5, 20, 59, 27, 558515)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='Exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam'),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 5, 20, 59, 27, 561210)),
        ),
        migrations.CreateModel(
            name='Exam_Soln',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exam_Soln', to='core.exam')),
                ('SolnSheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exam_Soln', to='core.solutionssheet')),
                ('soln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Exam_Soln', to='core.soln')),
            ],
        ),
        migrations.AlterField(
            model_name='soln',
            name='Exam',
            field=models.ManyToManyField(related_name='Solns', through='core.Exam_Soln', to='core.exam'),
        ),
    ]
