# Generated by Django 5.2.6 on 2026-01-21 17:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_donationtransactions_datetime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='Attachments',
        ),
        migrations.AddField(
            model_name='classroom',
            name='titile',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 19, 54, 33, 254572)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 19, 54, 33, 249524)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 19, 54, 33, 252990)),
        ),
        migrations.CreateModel(
            name='ClassRoomAttachment',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Attachments', models.FileField(default=None, null=True, upload_to='uploads/')),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Attachments', to='core.classroom')),
            ],
        ),
    ]
