# Generated by Django 5.2.6 on 2025-12-13 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_classroom_admin_alter_exam_createdat'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='User',
            new_name='OwnedBy',
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 0, 34, 10, 8857)),
        ),
    ]
