# Generated by Django 5.2.6 on 2026-01-21 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_classroom_attachments_classroom_titile_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='titile',
            new_name='Titile',
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 19, 56, 59, 1086)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 19, 56, 58, 995865)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 21, 19, 56, 58, 999498)),
        ),
    ]
