# Generated by Django 5.2.6 on 2025-12-13 23:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_user_question_ownedby_alter_exam_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='PreventOtherTabs',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 1, 6, 30, 281638)),
        ),
    ]
