# Generated by Django 5.2.6 on 2026-01-22 18:44

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_titile_classroom_titile_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomattachment',
            name='PaymentAccessMaxCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classroomattachment',
            name='PaymentExpireInterval_MIN',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='classroomattachment',
            name='paymentAmount',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='messages',
            name='classRoom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.classroom'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 22, 20, 44, 1, 705105)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 22, 20, 44, 1, 699520)),
        ),
        migrations.RemoveField(
            model_name='privileges',
            name='User',
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 22, 20, 44, 1, 703093)),
        ),
        migrations.AddField(
            model_name='privileges',
            name='User',
            field=models.ManyToManyField(default=1, related_name='Privileges', to=settings.AUTH_USER_MODEL),
        ),
    ]
