# Generated by Django 5.2.6 on 2025-12-14 18:54

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_settings_preventothertabs_alter_exam_createdat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 20, 54, 34, 323450)),
        ),
        migrations.CreateModel(
            name='classRoom_Exam',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Exams', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='classroom',
            name='Exams',
            field=models.ManyToManyField(related_name='ClassRooms', through='core.classRoom_Exam', to='core.exam'),
        ),
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('PreferedLang', models.TextField(default='en')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ProfileSettings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
