# Generated by Django 5.2.6 on 2026-01-23 14:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_classroomattachment_paymentaccessmaxcount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classroom',
            old_name='Titile',
            new_name='Title',
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 16, 54, 56, 800534)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 16, 54, 56, 795018)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 23, 16, 54, 56, 798574)),
        ),
    ]
