# Generated by Django 5.2.6 on 2025-12-14 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_exam_createdat_classroom_exam_classroom_exams_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 14, 21, 54, 17, 271432)),
        ),
        migrations.AlterField(
            model_name='settings',
            name='Duration_min',
            field=models.IntegerField(default=0),
        ),
    ]
