# Generated by Django 5.2.6 on 2025-12-15 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_exam_createdat_alter_settings_duration_min'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='Exam',
            new_name='Settings',
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 15, 22, 0, 14, 288556)),
        ),
    ]
