# Generated by Django 5.2.6 on 2026-01-25 22:37

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_rename_titile_classroom_title_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AttachmentLicence',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('uploadTime', models.DateTimeField(auto_now=True)),
                ('FileFingerPrint', models.TextField()),
                ('RequireSecurity', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='payment_attachment',
            name='attachmet',
        ),
        migrations.AddField(
            model_name='payment_attachment',
            name='classRoomAttachment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Payment_Attachment', to='core.classroomattachment'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 25, 22, 36, 19, 387997)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 25, 22, 36, 19, 382776)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 25, 22, 36, 19, 385908)),
        ),
        migrations.AddField(
            model_name='classroomattachment',
            name='attachmentLicence',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.attachmentlicence'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Attachments',
        ),
    ]
