# Generated by Django 5.2.6 on 2025-12-17 19:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_rename_exam_location_settings_alter_exam_createdat'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 17, 21, 20, 46, 164633)),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfileSettings', to=settings.AUTH_USER_MODEL),
        ),
    ]
