# Generated by Django 5.2.6 on 2026-01-25 23:20

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_attachmentlicence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='attachmentlicence',
            name='owner',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='attachmentLicence', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='Warnings',
            field=models.SmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='classroomattachment',
            name='attachmentLicence',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classRoomAttachment', to='core.attachmentlicence'),
        ),
        migrations.RemoveField(
            model_name='classroomattachment',
            name='classRoom',
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 25, 23, 19, 57, 877804)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 25, 23, 19, 57, 872455)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 25, 23, 19, 57, 875749)),
        ),
        migrations.AddField(
            model_name='classroomattachment',
            name='classRoom',
            field=models.ManyToManyField(related_name='Attachments', to='core.classroom'),
        ),
    ]
