# Generated by Django 5.2.6 on 2025-12-17 19:25

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_exam_createdat_alter_profilesettings_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 17, 21, 25, 43, 468294)),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ProfileSettings', to=settings.AUTH_USER_MODEL),
        ),
    ]
