# Generated by Django 5.2.6 on 2026-01-26 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_donationtransactions_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment_attachment',
            name='TransactionTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment_chatroom',
            name='TransactionTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='payment_classroom',
            name='TransactionTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 22, 17, 43, 105739)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 22, 17, 43, 100173)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 26, 22, 17, 43, 103601)),
        ),
    ]
