# Generated by Django 5.2.6 on 2026-01-29 18:27

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_payment_attachment_transactiontime_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomattachment',
            name='classRoom',
        ),
        migrations.AddField(
            model_name='profilesettings',
            name='socketID',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 20, 27, 2, 947868)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 20, 27, 2, 941691)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 20, 27, 2, 945602)),
        ),
        migrations.CreateModel(
            name='classRoom_ClassRoomAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('ClassRoomAttachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_clAttach', to='core.classroomattachment')),
                ('classRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cl_clAttach', to='core.classroom')),
            ],
        ),
    ]
