# Generated by Django 5.2.6 on 2025-12-17 19:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_exam_createdat_alter_profilesettings_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 17, 21, 30, 20, 680652)),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='PreferedLang',
            field=models.TextField(default='EN'),
        ),
    ]
