# Generated by Django 5.2.6 on 2026-01-29 18:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_classroomattachment_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomattachment',
            name='classRoom',
            field=models.ManyToManyField(related_name='Attachments', through='core.classRoom_ClassRoomAttachment', to='core.classroom'),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 20, 27, 20, 652835)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 20, 27, 20, 646924)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 1, 29, 20, 27, 20, 650495)),
        ),
    ]
