# Generated by Django 5.2.6 on 2025-12-19 17:17

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_exam_createdat_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='supportedLanguages',
            fields=[
                ('Name', models.CharField(max_length=2)),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 19, 19, 17, 38, 902783)),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='User',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Settings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='PreferedLang',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profiles', to='core.supportedlanguages'),
        ),
    ]
