# Generated by Django 5.2.6 on 2025-12-19 17:40

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_supportedlanguages_alter_exam_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2025, 12, 19, 19, 40, 32, 456205)),
        ),
        migrations.AlterField(
            model_name='profilesettings',
            name='PreferedLang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Profiles', to='core.supportedlanguages'),
        ),
    ]
