# Generated by Django 5.2.6 on 2026-01-31 23:18

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_classroomattachment_classroom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom_classroomattachment',
            name='isOrderDepenent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroomattachment',
            name='otherAttachmets',
            field=models.ManyToManyField(related_name='relatedAttachment', to='core.classroomattachment'),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 1, 18, 34, 456568)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 1, 18, 34, 450021)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 1, 18, 34, 454205)),
        ),
        migrations.CreateModel(
            name='AttachmentDependencies',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('jsonDep', models.JSONField()),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='core.classroomattachment')),
            ],
        ),
    ]
