# Generated by Django 5.2.6 on 2026-01-31 23:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_classroom_classroomattachment_isorderdepenent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 1, 33, 40, 987991)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 1, 33, 40, 981318)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 1, 1, 33, 40, 985596)),
        ),
    ]
