# Generated by Django 5.2.6 on 2026-02-06 14:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_alter_donationtransactions_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='scoringMode',
            field=models.IntegerField(choices=[(0, 'DEFAULT'), (1, 'MULTI_ANS_ONE_ENOUGH'), (2, 'MULTI_ANS_PARTITION')], default=0),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 6, 16, 56, 8, 100035)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 6, 16, 56, 8, 93414)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 6, 16, 56, 8, 97633)),
        ),
    ]
