# Generated by Django 5.2.6 on 2026-02-09 19:18

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_question_scoringmode_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='dependenciesRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependentTable', models.TextField()),
                ('dependOnTable', models.TextField()),
                ('field_value', models.JSONField()),
            ],
        ),
        migrations.RenameField(
            model_name='privileges',
            old_name='User',
            new_name='Users',
        ),
        migrations.AddField(
            model_name='classroomattachment',
            name='name',
            field=models.TextField(default='NO_NAME'),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 9, 21, 18, 53, 108925)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 9, 21, 18, 53, 101026)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 9, 21, 18, 53, 105372)),
        ),
        migrations.CreateModel(
            name='Committe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isOpened', models.BooleanField(default=False)),
                ('Exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.exam')),
                ('clRoom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroom')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspector', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteAllowedList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present', models.BooleanField(default=False)),
                ('committe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.committe')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowedIn', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommitteEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventStr', models.TextField()),
                ('committe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Events', to='core.committe')),
            ],
        ),
        migrations.CreateModel(
            name='WatchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.classroomattachment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachmentHistory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
