# Generated by Django 5.2.6 on 2026-02-10 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_dependenciesrepo_rename_user_privileges_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomattachment',
            name='isOrdered',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classroomattachment',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 10, 21, 16, 11, 128955)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 10, 21, 16, 11, 120828)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 10, 21, 16, 11, 125025)),
        ),
    ]
