# Generated by Django 5.2.6 on 2026-02-13 19:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_classroomattachment_isordered_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dependenciesrepo',
            old_name='field_value',
            new_name='allowedFields',
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 21, 19, 10, 72464)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 21, 19, 10, 64779)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 13, 21, 19, 10, 69053)),
        ),
    ]
