# Generated by Django 5.2.6 on 2026-02-14 15:21

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_rename_field_value_dependenciesrepo_allowedfields_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='OwnedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='OwnedClasses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 17, 21, 13, 183713)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 17, 21, 13, 175760)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 17, 21, 13, 179932)),
        ),
    ]
