# Generated by Django 5.2.6 on 2026-02-14 16:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_classroom_ownedby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomattachment',
            name='isOrdered',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 18, 56, 47, 655820)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 18, 56, 47, 647838)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 18, 56, 47, 652267)),
        ),
    ]
