# Generated by Django 5.2.6 on 2026-02-14 17:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_classroomattachment_isordered_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='attachmentsCounter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 19, 0, 5, 303108)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 19, 0, 5, 293580)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 19, 0, 5, 298196)),
        ),
    ]
