# Generated by Django 5.2.6 on 2026-02-14 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_attachmentlicence_owner_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom_classroomattachment',
            name='order',
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 19, 37, 10, 801327)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 19, 37, 10, 792387)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 19, 37, 10, 796915)),
        ),
    ]
