# Generated by Django 5.2.6 on 2026-02-14 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_remove_classroom_classroomattachment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom_classroomattachment',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 19, 51, 8, 866269)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 19, 51, 8, 858026)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 19, 51, 8, 862576)),
        ),
    ]
