# Generated by Django 5.2.6 on 2026-02-14 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_classroom_classroomattachment_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroomattachment',
            name='thumbnail',
            field=models.FileField(default=None, null=True, upload_to='thumbnails/'),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 21, 7, 8, 476350)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 21, 7, 8, 467682)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 14, 21, 7, 8, 472818)),
        ),
    ]
