# Generated by Django 5.2.6 on 2026-02-20 14:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_classroomattachment_thumbnail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committe',
            name='isExamStarted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 16, 46, 12, 243617)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 16, 46, 12, 235785)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 16, 46, 12, 240174)),
        ),
    ]
