# Generated by Django 5.2.6 on 2026-02-20 21:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_committe_isexamstarted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilesettings',
            name='joinedCommitte',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.committe'),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 23, 46, 43, 313730)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 23, 46, 43, 305986)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 23, 46, 43, 310261)),
        ),
    ]
