# Generated by Django 5.2.6 on 2026-02-20 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_profilesettings_joinedcommitte_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilesettings',
            name='joinedCommitte',
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 0, 37, 42, 308363)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 0, 37, 42, 299565)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 0, 37, 42, 303959)),
        ),
    ]
