# Generated by Django 5.2.6 on 2026-02-20 22:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_remove_profilesettings_joinedcommitte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='committe',
            name='isInspectorIn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 0, 58, 23, 719196)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 0, 58, 23, 710742)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 21, 0, 58, 23, 715245)),
        ),
    ]
