# Generated by Django 5.2.6 on 2026-02-24 22:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_committe_isinspectorin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shareWithLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tableName', models.TextField()),
                ('address', models.TextField()),
                ('itemID', models.IntegerField()),
                ('command', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 25, 0, 26, 33, 966904)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 25, 0, 26, 33, 958895)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 25, 0, 26, 33, 963194)),
        ),
    ]
