# Generated by Django 5.2.6 on 2026-03-10 17:20

import core.services.types.questionType
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_alter_donationtransactions_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 19, 20, 17, 503068)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 19, 20, 17, 492281)),
        ),
        migrations.AlterField(
            model_name='question',
            name='Type',
            field=models.IntegerField(choices=[(0, 'MCQ_ONE_ANS'), (1, 'MCQ_MORE_ANS'), (2, 'WRITTEN_QUETION'), (3, 'COMPLETE')], default=core.services.types.questionType.QuestionType['MCQ_ONE_ANS']),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 10, 19, 20, 17, 497276)),
        ),
    ]
