# Generated by Django 5.2.6 on 2026-03-10 22:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_donationtransactions_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 11, 0, 37, 53, 291300)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 11, 0, 37, 53, 283548)),
        ),
        migrations.AlterField(
            model_name='question',
            name='createdAt',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 11, 0, 37, 53, 287628)),
        ),
    ]
