# Generated by Django 5.2.6 on 2026-03-22 20:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_alter_donationtransactions_datetime_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Messages_Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='uploads/chats/')),
            ],
        ),
        migrations.RemoveField(
            model_name='messages',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='classRoom',
        ),
        migrations.RemoveField(
            model_name='messages',
            name='text',
        ),
        migrations.AddField(
            model_name='messages',
            name='attachments',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='core.chatroom'),
        ),
        migrations.AddField(
            model_name='messages',
            name='chatRoom',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.messages'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='classroomattachment',
            name='Attachments',
            field=models.FileField(default=None, null=True, upload_to='uploads/data/classRoom/'),
        ),
        migrations.AlterField(
            model_name='classroomattachment',
            name='thumbnail',
            field=models.FileField(default=None, null=True, upload_to='uploads/thumbnails/classRoom'),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 22, 44, 28, 517305)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 22, 44, 28, 508571)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 22, 44, 28, 513170)),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('destination_Code', models.TextField()),
                ('Owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='chatroom',
            name='Notifications',
            field=models.ManyToManyField(related_name='chatRoom', through='core.Messages', to='core.notification'),
        ),
        migrations.AddField(
            model_name='messages',
            name='notification',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.notification'),
            preserve_default=False,
        ),
    ]
