# Generated by Django 5.2.6 on 2026-03-22 21:18

import core.services.utils.notification
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_messages_attachment_remove_messages_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reading_status',
            field=models.IntegerField(choices=[(0, 'PENDING'), (1, 'ARRIVED'), (2, 'READED'), (3, 'DELETED')], default=core.services.utils.notification.NotificationStatus['PENDING']),
        ),
        migrations.AlterField(
            model_name='donationtransactions',
            name='Datetime',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 23, 18, 50, 324127)),
        ),
        migrations.AlterField(
            model_name='exam',
            name='CreatedAt',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 23, 18, 50, 311684)),
        ),
        migrations.AlterField(
            model_name='solutionssheet',
            name='LastUpdate',
            field=models.DateTimeField(default=datetime.datetime(2026, 3, 22, 23, 18, 50, 319149)),
        ),
    ]
