from typing import Protocol, Iterable, TypeVar
from django.db import models

T = TypeVar("T", bound=models.Model)

class ManyToManyManager(Protocol[T]):
    def all(self) -> models.QuerySet[T]: ...
    def add(self, *objs: T) -> None: ...
    def remove(self, *objs: T) -> None: ...
    def set(self, objs: Iterable[T]) -> None: ...
#------------------